#!/usr/bin/env ruby

require "uri"
require "net/http"
require "json"
require "pathname"

dir = File.dirname(Pathname.new(__FILE__).realpath)
file = File.read("#{dir}/.env").split[0]
ENV = Hash[*file.split("=").flatten(1)]

command = if ARGV[0] == "gcm" # aka generate commit message
            "gitcommit"
          else
            "snippet"
          end

url = "https://api.openai.com/v1/completions"

if command == "gitcommit"
  diff = `git diff --unified=0 --no-color`
  branch = `git branch --show-current`.gsub("\n", "")

  prompt = 'Return only the commit message for the following diff changes.'
  if !['master', 'main'].include? branch
    prompt += ' Start the commit message with the task number from the branch name: ' +  branch + '.\n\n'
  else
    prompt += '\n\n'
  end
  prompt += diff
elsif command == "snippet"
  prompt = ARGV[0] + " .Return only the code."
  filename = ARGV[1] || "gpt_output-#{Time.now.strftime("%Y-%m-%d_%H:%M:%S")}.txt"
end

headers = {
  "Authorization": "Bearer #{ENV['OPENAI_ACCESS_TOKEN']}",
  "Content-Type": "application/json"
}

data = {
  model: "text-davinci-003",
  prompt: prompt,
  temperature: 0.2,
  max_tokens: 300
}

response = Net::HTTP.post(URI(url), data.to_json, headers)

json = JSON.parse(response.body)

text = json["choices"].map { |c| c["text"] }[0]

puts text
puts "\n"

File.write(filename, text) if filename
