#!/usr/bin/env ruby

require "uri"
require "net/http"
require "json"

file = File.read(".env").split[0]
ENV = Hash[*file.split("=").flatten(1)]

url = "https://api.openai.com/v1/completions"
prompt = ARGV[0] + " .Return only the code."
filename = ARGV[1] || "output.txt"

headers = {
  "Authorization": "Bearer #{ENV['OPENAI_ACCESS_TOKEN']}",
  "Content-Type": "application/json"
}

data = {
  model: "text-davinci-003",
  prompt: prompt,
  temperature: 0.2,
  max_tokens: 300
}

response = Net::HTTP.post(URI(url), data.to_json, headers)

json = JSON.parse(response.body)

text = json["choices"].map { |c| c["text"] }[0]

puts text

File.write(filename, text)
